import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
// @ts-ignore

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'Usage',
      items: [{ type: 'autogenerated', dirName: 'usage' }],
      link: {
        type: 'doc',
        id: 'usage/index',
      },
    },
    {
      type: 'category',
      label: 'API',
      items: [{ type: 'autogenerated', dirName: 'api' }],
      link: {
        type: 'doc',
        id: 'api/modules/src_main',
      },
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [{ type: 'autogenerated', dirName: 'contributing' }],
      link: {
        type: 'doc',
        id: 'contributing/index',
      },
    },
  ],
};

export default sidebars;
